#!/bin/sh

if [ -x /usr/bin/apt-key ]; then
    /usr/bin/apt-key add /usr/share/keyrings/netrunner-keyring.gpg
    /usr/bin/apt-key add /usr/share/keyrings/netrunner-ppa-keyring.gpg
    /usr/bin/apt-key add /usr/share/keyrings/medibuntu-keyring.gpg
    /usr/bin/apt-key add /usr/share/keyrings/netrunner-simpleclone.gpg
    /usr/bin/apt-key add /usr/share/keyrings/ubuntu-wine-ppa.gpg
    /usr/bin/apt-key add /usr/share/keyrings/cinnamon-stable-ppa.gpg
fi
